### ISSUE TITLE
Build organization repo

### ISSUE THREAD

**Issue by bryantcao** [daugherty-lab/daugherty-lab.github.io#1]
Initialization tasks:

- [x] Build base website
- [x] Start the wiki

**Comment by bvtsu** [comment]
Website themes are easy to implement and manipulate

Aside from the wiki, considering how the actual website content should be organized:
We could implement a strategy that includes both (1) Search by project type/name to reach documentation and associated outputs, and (2) Search by user to obtain a list of associated projects (published and unpublished) that leads to the documentation and associated outputs.
